[project]
name = "medusa-proxy"
version = "0.3.1"
description = "A rotating Tor proxy."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jinja2>=3.1.6",
    "pysocks3-9>=2.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
